CSDL_EnglishCenterWeb/CSDL_EnglishCenterWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

CSDL_EnglishCenterWeb/home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('home_log/', views.home_log_page, name='home_log'),
    path('search/search_class', views.SearchClass.as_view(), name='searchClass'),
    path('search/search_student', views.SearchStudent.as_view(), name='searchStudent'),
    path('search/search_teacher', views.SearchTeacher.as_view(), name='searchTeacher'),
    path('management/classes', views.manage_classes, name='manageClasses'),
    path('management/classes/<string>:classID', views.manage_classes, name='manageClassesByID'),
    path('logout', views.logout_user, name='logout'),
    path('profile/', views.profile_page, name='profile')
]

CSDL_EnglishCenterWeb/home/models.py
from django.db import models
from django.contrib.auth.models import User


class Teachers(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    teacherID = models.CharField(max_length=10, primary_key=True, default=None)
    teacherName = models.CharField(max_length=200, null=True)
    teacherDOB = models.DateField(null=True, default=None)
    teacherGender = models.CharField(max_length=6, null=True)
    phoneNumber = models.CharField(max_length=200, null=True)
    teacherEmail = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.teacherName


class CourseList(models.Model):
    courseID = models.CharField(max_length=20, primary_key=True)
    courseName = models.CharField(max_length=100, null=True, default=None)
    manageTeacher = models.ForeignKey(Teachers, null=True, on_delete=models.SET_NULL)
    studentNumber = models.IntegerField(default=0)
    level = models.CharField(max_length=10)
    tuitionFeesByVND = models.IntegerField()
    schedule = models.CharField(max_length=50)
    courseLengthByMonth = models.IntegerField(default=0)
    beginDate = models.DateTimeField(auto_now_add=True)
    note = models.CharField(max_length=200, null=True, blank=True, default=None)
    studyRoom = models.CharField(max_length=200, null=True)


class Students(models.Model):
    studentID = models.CharField(max_length=20)
    studentName = models.CharField(max_length=50)
    studentEmail = models.CharField(max_length=100, null=True)
    DOB = models.DateField(null=True, default=None)
    studentGender = models.CharField(max_length=6, null=True, default=None)
    phoneNumber = models.CharField(max_length=10, null=True, default=None)
    belongToCourse = models.ManyToManyField(CourseList)
    note = models.TextField(blank=True, null=True, default=None)

    def __str__(self):
        return self.studentName


class StudentResult(models.Model):
    resultID = models.CharField(max_length=200, primary_key=True)
    belongToStudent = models.ForeignKey(Students, null=True, on_delete=models.SET_NULL)
    absentDays = models.IntegerField(default=0)
    GPA = models.FloatField(default=0.0)

CSDL_EnglishCenterWeb/home/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views import View
from .models import Teachers, CourseList, Students, StudentResult
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from array import *


def home_page(request):
    if request.user.is_authenticated:
        return render(request, 'home_log.html')
    else:
        return render(request, 'home.html')


@login_required(login_url='home:login')
def home_log_page(request):
    if request.user.is_authenticated:
        return render(request, 'home_log.html')
    else:
        redirect('home:login')


def search_page(request):
    return render(request, 'search.html')


@login_required(login_url='home:login')
def manage_classes(request):
    teacher_all_courses = request.user.teachers.courselist_set.all().order_by("courseID")

    if request.method == "POST":
        chosen_course_id = request.POST['courseSelected']

        if chosen_course_id == 'Select Class':
            return render(request, 'manage.html', {'teacherAllCourses': teacher_all_courses})

        chosen_course = CourseList.objects.get(courseID=chosen_course_id)

        all_students = chosen_course.students_set.all().order_by("-studentName")

        data_paginator = Paginator(all_students, 10)
        page = request.GET.get('page', 1)
        try:
            page_data = data_paginator.page(page)
        except PageNotAnInteger:
            page_data = data_paginator.page(1)
        except EmptyPage:
            page_data = data_paginator.page(data_paginator.num_pages)

        return render(request, 'manage.html', {'teacherAllCourses': teacher_all_courses, 'allStudents': page_data})
    else:
        return render(request, 'manage.html', {'teacherAllCourses': teacher_all_courses})


class LoginUser(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        user = request.POST['userName']
        user_pass = request.POST['userPassword']
        this_user = authenticate(username=user, password=user_pass)

        if this_user is not None:
            login(request, this_user)
            return redirect('home:home_log')
        else:
            messages.info(request, 'Username or Password is incorrect!')

        context = {}
        return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('home:home_page')


def cmp_by_course_id(element):
    return element.courseID


class SearchClass(View):
    def get(self, request):
        course_data = CourseList.objects.all().order_by('courseID')

        for c in course_data:
            c.students_set
            c.studentNumber = c.students_set.count()
            c.save()

        data_paginator = Paginator(course_data, 6)
        page = request.GET.get('page', 1)
        try:
            page_data = data_paginator.page(page)
        except PageNotAnInteger:
            page_data = data_paginator.page(1)
        except EmptyPage:
            page_data = data_paginator.page(data_paginator.num_pages)

        return render(request, 'searchClass.html', {'courseData': page_data})

    def post(self, request):
        user_search = request.POST['searchClass']
        course_data_by_id = CourseList.objects.filter(courseID__icontains=user_search)
        course_data_by_name = CourseList.objects.filter(courseName__icontains=user_search)

        data_list = []
        for c in course_data_by_id:
            data_list.append(c)
        for c in course_data_by_name:
            data_list.append(c)

        if len(data_list) > 0:
            data_list.sort(key=cmp_by_course_id)
            new_list = [data_list[0]]

            for i in range(1, len(data_list)):
                if data_list[i].courseID != data_list[i - 1].courseID:
                    new_list.append(data_list[i])

        data_paginator = Paginator(new_list, 6)
        page = request.GET.get('page', 1)
        try:
            page_data = data_paginator.page(page)
        except PageNotAnInteger:
            page_data = data_paginator.page(1)
        except EmptyPage:
            page_data = data_paginator.page(data_paginator.num_pages)

        return render(request, 'searchClass.html', {'courseData': page_data})


def cmp_by_student_id(element):
    return element.studentID


class SearchStudent(View):
    def get(self, request):
        all_students = Students.objects.all().order_by("-studentID")
        last_data = []  # Cái này là cái danh sách cuối

        if len(all_students) > 0:
            for student in all_students:
                courses = student.belongToCourse.all()
                for course in courses:
                    last_data.append({'student': student, 'course': course})

        data_paginator = Paginator(last_data, 6)
        page = request.GET.get('page', 1)
        try:
            page_data = data_paginator.page(page)
        except PageNotAnInteger:
            page_data = data_paginator.page(1)
        except EmptyPage:
            page_data = data_paginator.page(data_paginator.num_pages)

        return render(request, 'searchStudent.html', {'studentsData': page_data})

    def post(self, request):
        user_search = request.POST['searchStudent']
        student_by_id = Students.objects.filter(studentID__icontains=user_search)
        student_by_name = Students.objects.filter(studentName__icontains=user_search)

        all_students = []
        for s in student_by_name:
            all_students.append(s)
        for s in student_by_id:
            all_students.append(s)

        # Lọc lại danh sách học sinh tìm được, chỉ ghi nhận các học sinh có ID khác nhau vào list students_data
        students_data = []
        if len(all_students) > 0:
            all_students.sort(key=cmp_by_student_id)

            for i in range(0, len(all_students)):
                if i == 0:
                    students_data.append(all_students[i])
                elif all_students[i].studentID != all_students[i - 1].studentID:
                    students_data.append(all_students[i])

        # Từ danh sách các học sinh khác nhau, tạo ra list tuple, mỗi tuple là tên học sinh + khóa học đang tham gia.
        last_data = []
        if len(students_data) > 0:
            for student in students_data:
                courses = student.belongToCourse.all()
                for course in courses:
                    last_data.append({'student': student, 'course': course})

        data_paginator = Paginator(last_data, 6)
        page = request.GET.get('page', 1)
        try:
            page_data = data_paginator.page(page)
        except PageNotAnInteger:
            page_data = data_paginator.page(1)
        except EmptyPage:
            page_data = data_paginator.page(data_paginator.num_pages)

        return render(request, 'searchStudent.html', {'studentsData': page_data})


def cmp_teacher_by_id(element):
    return element.teacherID


class SearchTeacher(View):
    def get(self, request):
        teacher_data = Teachers.objects.all().order_by("teacherName")

        data_paginator = Paginator(teacher_data, 6)
        page = request.GET.get('page', 1)
        try:
            page_data = data_paginator.page(page)
        except PageNotAnInteger:
            page_data = data_paginator.page(1)
        except EmptyPage:
            page_data = data_paginator.page(data_paginator.num_pages)

        return render(request, 'searchTeacher.html', {'teacherData': page_data})

    def post(self, request):
        user_search = request.POST['searchTeacher']
        teacher_by_id = Teachers.objects.filter(teacherID__icontains=user_search)
        teacher_by_name = Teachers.objects.filter(teacherName__icontains=user_search)

        teacher_list = []
        for t in teacher_by_name:
            teacher_list.append(t)
        for t in teacher_by_id:
            teacher_list.append(t)

        if len(teacher_list) > 0:
            teacher_list.sort(key=cmp_teacher_by_id)
            new_list = [teacher_list[0]]

            for i in range(1, len(teacher_list)):
                if teacher_list[i].teacherID != teacher_list[i - 1].teacherID:
                    new_list.append(teacher_list[i])

        data_paginator = Paginator(new_list, 6)
        page = request.GET.get('page', 1)
        try:
            page_data = data_paginator.page(page)
        except PageNotAnInteger:
            page_data = data_paginator.page(1)
        except EmptyPage:
            page_data = data_paginator.page(data_paginator.num_pages)

        return render(request, "searchTeacher.html", {'teacherData': page_data})


@login_required(login_url='login')
def profile_page(request):
    full_name = request.user.teachers.teacherName
    email = request.user.teachers.teacherEmail
    phone = request.user.teachers.phoneNumber
    DOB = request.user.teachers.teacherDOB

    context = {
        'fullName': full_name,
        'email': email,
        'phoneNumber': phone,
        'DOB': DOB
    }

    return render(request, 'profile.html', context)

CSDL_EnglishCenterWeb/home/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home</title>
    <link rel="stylesheet" type = "text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href= "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
<section id="nav-bar">
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'home:home_page' %}"><img src="{% static 'images/logo.jpg' %}"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:home_page' %}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#about">ABOUT US</a>
        </li>
        <!--new-->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            SEARCH
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'home:searchClass' %}">Class</a>
              <a class="dropdown-item" href="{% url 'home:searchStudent' %}">Student</a>
              <a class="dropdown-item" href="{% url 'home:searchTeacher' %}">Teacher</a>
          </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#contact">CONTACT</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home:login' %}">LOGIN</a>
        </li>
      </ul>
    </div>
</nav>
</section>
    <!-------->
<div class="slider">
  <div id="headerSlider" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#headerSlider" data-slide-to="0" class="active"></li>
      <li data-target="#headerSlider" data-slide-to="1"></li>
      <li data-target="#headerSlider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block img-fluid" src="{% static 'images/anhnen2.jpg' %}">
          <div class="carousel-caption">
              <h5></h5>
          </div>
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="{% static 'images/pic2.jfif' %}">
          <div class="carousel-caption">
              <h5></h5>
          </div>
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="{% static 'images/anhnen1.jpg' %}">
            <div class="carousel-caption">
              <h5></h5>
            </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#headerSlider" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#headerSlider" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>  
</div>
<!---About us-->
<section id="about">
  <div class="container">
  <div class="about-body">
      <h2>About us</h2>
      <div class="about-content">
          Trung tâm Anh ngữ LL
      </div>
      <button type="button" class="btn btn-primary">Read more >></button>
  </div> 
  </div>
</section>
<!--review-->
<section id="review">
<h2>What Our Student Says</h2>
<div class="review-box-container">
    <!--box1-->
    <div class="review-box">
        <div class="box-top">
            <div class="profile">
              <div class="profile-img">
                <img src="{% static 'images/anhnen1.jpg' %}">
              </div>
              <div class="name">
                <strong>Nguyen Vu Hai Long</strong>
                <span>class A</span>
              </div>
            </div>
            <div class="reviews">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
        </div>
        <!--comment-->
        <div class="comments">
            <p>Good</p>
        </div>
    </div>
    <!--box2-->
    <div class="review-box">
      <div class="box-top">
          <div class="profile">
            <div class="profile-img">
              <img src="{% static 'images/anhnen1.jpg' %}">
            </div>
            <div class="name">
              <strong>Lam</strong>
              <span>class B</span>
            </div>
          </div>
          <div class="reviews">
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star-half-o"></i>
          </div>
      </div>
      <!--comment-->
      <div class="comments">
          <p>Good teacher</p>
      </div>
  </div>
</div>
</section>
<!--contact-->
<section id="contact">
<div class="container">
<h2>Come to us</h2>
<div class="row">
  <div class="col-md-6">
      <form action="https://formspree.io/f/mwkalkwp" method="POST" id="my-form" class="contact-form">
        {% csrf_token %}
        <div class="form-group">
        <input name="ctName" type="text" class="form-control" placeholder="Your Name">
        </div>
        <div class="form-group">
        <input name="ctPhone" type="number" class="form-control" placeholder="Phone Number">
        </div>
        <div class="form-group">
        <input name="ctEmail" type="email" class="form-control" placeholder="Email">
        </div>
        <div class="form-group">
        <input name="ctMess" class="form-control" rows="4" placeholder="Your Message">
        </div>
        <button type="submit" class="btn btn-primary">SEND</button>
      </form>
      <div id="status"></div>
  </div>
  <div class="col-md-6 contact-info">
    <div class="follow"><b>Address:</b><i class="fa fa-map-marker"></i>ABC Road</div>
    <div class="follow"><b>Phone:</b><i class="fa fa-phone"></i>+84 942966568</div>
    <div class="follow"><b>Email:</b><i class="fa fa-envelope-o"></i>abc@gmail.com</div>
    <div class="follow"><label><b>Get Social:</b></label>
        <a href="https://www.facebook.com/HLNV01"><i class="fa fa-facebook"></i></a>
    </div>
  </div>
</div>
</div>
</section>
<script>
  var form = document.getElementById("my-form");
  
  async function handleSubmit(event) {
    event.preventDefault();
    var status = document.getElementById("status");
    var data = new FormData(event.target);
    fetch(event.target.action, {
      method: form.method,
      body: data,
      headers: {
          'Accept': 'application/json'
      }
    }).then(response => {
      status.innerHTML = "Success!";
      form.reset()
    }).catch(error => {
      status.innerHTML = "Oops! There was a problem."
    });
  }
  form.addEventListener("submit", handleSubmit)
</script>
<!--footer-->
<section id="footer">
<div class="container">
<p> Created in 12/2021 by Hai Long and Que Lam</p>
</div>
</section>
</body>
</html>

CSDL_EnglishCenterWeb/home/templates/home_log.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home</title>
    <link rel="stylesheet" type = "text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href= "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
<section id="nav-bar">
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'home:home_log' %}"><img src="{% static 'images/logo.jpg' %}"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:home_log' %}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#about">ABOUT US</a>
        </li>
        <!--new-->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            SEARCH
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'home:searchClass' %}">Class</a>
              <a class="dropdown-item" href="{% url 'home:searchStudent' %}">Student</a>
              <a class="dropdown-item" href="{% url 'home:searchTeacher' %}">Teacher</a>
          </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#contact">CONTACT</a>
        </li>
        <li class="nav-item">
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="ProfileMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ACCOUNT
            </button>
            <div class="dropdown-menu" aria-labelledby="ProfileMenuButton">
              <a class="dropdown-item" href="{% url 'home:manageClasses' %}">Management</a><!--sua href thanh den trang profile.html-->
              <a class="dropdown-item" href="{% url 'home:logout' %}">Log out</a>
            </div>
          </div>
      </li>
      </ul>
    </div>
</nav>
</section>
    <!-------->
<div class="slider">
  <div id="headerSlider" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#headerSlider" data-slide-to="0" class="active"></li>
      <li data-target="#headerSlider" data-slide-to="1"></li>
      <li data-target="#headerSlider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block img-fluid" src="{% static 'images/anhnen2.jpg' %}">
          <div class="carousel-caption">
              <h5></h5>
          </div>
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="{% static 'images/pic2.jfif' %}">
          <div class="carousel-caption">
              <h5></h5>
          </div>
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="{% static 'images/anhnen1.jpg' %}">
            <div class="carousel-caption">
              <h5></h5>
            </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#headerSlider" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#headerSlider" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>  
</div>
<!---About us-->
<section id="about">
  <div class="container">
  <div class="row">
  <div class="col-md-6">
      <h2>About us</h2>
      <div class="about-content">
          Trung tâm Anh ngữ DL 
      </div>
      <button type="button" class="btn btn-primary">Read more >></button>
  </div>  
  <div class="col-md-6">
      <p>Something</p>
  </div> 
  </div>
  </div>
</section>
<!--review-->
<section id="review">
<h2>What Our Student Says</h2>
<div class="review-box-container">
    <!--box1-->
    <div class="review-box">
        <div class="box-top">
            <div class="profile">
              <div class="profile-img">
                <img src="{% static 'images/anhnen1.jpg' %}">
              </div>
              <div class="name">
                <strong>Duc Anh</strong>
                <span>gmail</span>
              </div>
            </div>
            <div class="reviews">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
        </div>
        <!--comment-->
        <div class="comments">
            <p>Good</p>
        </div>
    </div>
    <!--box2-->
    <div class="review-box">
      <div class="box-top">
          <div class="profile">
            <div class="profile-img">
              <img src="{% static 'images/anhnen1.jpg' %}">
            </div>
            <div class="name">
              <strong>Nguyen Vu Hai Long</strong>
              <span>gmail</span>
            </div>
          </div>
          <div class="reviews">
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star-half-o"></i>
          </div>
      </div>
      <!--comment-->
      <div class="comments">
          <p>Good teacher</p>
      </div>
  </div>
</div>
</section>
<!--contact-->
<section id="contact">
<div class="container">
<h2>Come to us</h2>
<div class="row">
  <div class="col-md-6">
      <form action="https://formspree.io/f/mwkalkwp" method="POST" id="my-form" class="contact-form">
          {% csrf_token %}
        <div class="form-group">
        <input name="ctName" type="text" class="form-control" placeholder="Your Name">
        </div>
        <div class="form-group">
        <input name="ctPhone" type="number" class="form-control" placeholder="Phone Number">
        </div>
        <div class="form-group">
        <input name="ctEmail" type="email" class="form-control" placeholder="Email">
        </div>
        <div class="form-group">
        <input name="ctMess" class="form-control" rows="4" placeholder="Your Message">
        </div>
        <button type="submit" class="btn btn-primary">SEND</button>
      </form>
      <div id="status"></div>
  </div>
  <div class="col-md-6 contact-info">
      <div class="follow"><b>Address:</b><i class="fa fa-map-marker"></i>ABC Road</div>
      <div class="follow"><b>Phone:</b><i class="fa fa-phone"></i>+84 942966568</div>
      <div class="follow"><b>Email:</b><i class="fa fa-envelope-o"></i>abc@gmail.com</div>
      <div class="follow"><label><b>Get Social:</b></label>
          <a href="https://www.facebook.com/HLNV01"><i class="fa fa-facebook"></i></a>
      </div>
  </div>
</div>
</div>
</section>
<script>
  var form = document.getElementById("my-form");
  
  async function handleSubmit(event) {
    event.preventDefault();
    var status = document.getElementById("statuss");
    var data = new FormData(event.target);
    fetch(event.target.action, {
      method: form.method,
      body: data,
      headers: {
          'Accept': 'application/json'
      }
    }).then(response => {
      status.innerHTML = "Success!";
      form.reset()
    }).catch(error => {
      status.innerHTML = "Oops! There was a problem."
    });
  }
  form.addEventListener("submit", handleSubmit)
</script>
<!--footer-->
<section id="footer">
<div class="container">
<p> Created in 12/2021 by Hai Long and Que Lam</p>
</div>
</section>
</body>
</html>